# Generated by Django 5.1.2 on 2024-10-20 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_add_slug_to_product"),
    ]

    operations = [
        migrations.RunSQL(
            # SQL for applying the migration (inserting data)
            sql="""
                INSERT INTO store_collection (title) 
                VALUES ('collection1');
            """,
            # SQL for rolling back the migration (deleting data)
            reverse_sql="""
                DELETE FROM store_collection 
                WHERE title = 'collection1';
            """,
        ),
    ]
